# permissions for end users to view demodeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demodeployment-viewer-role
rules:
- apiGroups:
  - k8stest.com
  resources:
  - demodeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8stest.com
  resources:
  - demodeployments/status
  verbs:
  - get
